# Generated by Django 4.1 on 2024-11-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_alter_sliderimage_options_sliderimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
